// Code generated by pricing/gen. DO NOT EDIT.
//
// Source: litellm, fetched 2026-08-02T22:34:49Z.
// Regenerate with: go generate ./pricing

package pricing

// defaultPrices is the compiled-in price table. It serves every lookup
// that the override and remote layers do not answer: no UseRemote, no
// network, or a first refresh still in flight.
//
// Rates are USD per 1,000,000 tokens. A zero cache rate means the feed
// published none, and cacheRates falls back to the family multiplier.
var defaultPrices = map[string]Price{
	// Anthropic
	"claude-opus-5":     {InputPerMTok: 5, OutputPerMTok: 25, CacheWritePerMTok: 6.25, CacheReadPerMTok: 0.5},
	"claude-opus-4-6":   {InputPerMTok: 5, OutputPerMTok: 25, CacheWritePerMTok: 6.25, CacheReadPerMTok: 0.5},
	"claude-opus-4-5":   {InputPerMTok: 5, OutputPerMTok: 25, CacheWritePerMTok: 6.25, CacheReadPerMTok: 0.5},
	"claude-opus-4-1":   {InputPerMTok: 15, OutputPerMTok: 75, CacheWritePerMTok: 18.75, CacheReadPerMTok: 1.5},
	"claude-sonnet-5":   {InputPerMTok: 2, OutputPerMTok: 10, CacheWritePerMTok: 2.5, CacheReadPerMTok: 0.2},
	"claude-sonnet-4-6": {InputPerMTok: 3, OutputPerMTok: 15, CacheWritePerMTok: 3.75, CacheReadPerMTok: 0.3},
	"claude-sonnet-4-5": {InputPerMTok: 3, OutputPerMTok: 15, CacheWritePerMTok: 3.75, CacheReadPerMTok: 0.3},
	"claude-sonnet-4":   {InputPerMTok: 3, OutputPerMTok: 15, CacheWritePerMTok: 3.75, CacheReadPerMTok: 0.3},
	"claude-haiku-4-5":  {InputPerMTok: 1, OutputPerMTok: 5, CacheWritePerMTok: 1.25, CacheReadPerMTok: 0.1},
	"claude-haiku-3-5":  {InputPerMTok: 0.8, OutputPerMTok: 4, CacheWritePerMTok: 1, CacheReadPerMTok: 0.08},

	// OpenAI
	"gpt-4o":       {InputPerMTok: 2.5, OutputPerMTok: 10, CacheReadPerMTok: 1.25},
	"gpt-4o-mini":  {InputPerMTok: 0.15, OutputPerMTok: 0.6, CacheReadPerMTok: 0.075},
	"gpt-4.1":      {InputPerMTok: 2, OutputPerMTok: 8, CacheReadPerMTok: 0.5},
	"gpt-4.1-mini": {InputPerMTok: 0.4, OutputPerMTok: 1.6, CacheReadPerMTok: 0.1},
	"gpt-4.1-nano": {InputPerMTok: 0.1, OutputPerMTok: 0.4, CacheReadPerMTok: 0.025},
	"o3":           {InputPerMTok: 2, OutputPerMTok: 8, CacheReadPerMTok: 0.5},
	"o3-mini":      {InputPerMTok: 1.1, OutputPerMTok: 4.4, CacheReadPerMTok: 0.55},
	"o4-mini":      {InputPerMTok: 1.1, OutputPerMTok: 4.4, CacheReadPerMTok: 0.275},

	// Google
	"gemini-2.5-pro":   {InputPerMTok: 1.25, OutputPerMTok: 10, CacheReadPerMTok: 0.125},
	"gemini-2.5-flash": {InputPerMTok: 0.3, OutputPerMTok: 2.5, CacheReadPerMTok: 0.03},
	"gemini-2.0-flash": {InputPerMTok: 0.1, OutputPerMTok: 0.4, CacheReadPerMTok: 0.025},

	// Zhipu / Z.ai GLM
	"glm-5.1":     {InputPerMTok: 1.4, OutputPerMTok: 4.4, CacheReadPerMTok: 0.26},
	"glm-5":       {InputPerMTok: 1, OutputPerMTok: 3.2, CacheReadPerMTok: 0.2},
	"glm-4.7":     {InputPerMTok: 0.6, OutputPerMTok: 2.2, CacheReadPerMTok: 0.11},
	"glm-4.6":     {InputPerMTok: 0.6, OutputPerMTok: 2.2, CacheReadPerMTok: 0.11},
	"glm-4.5":     {InputPerMTok: 0.6, OutputPerMTok: 2.2, CacheReadPerMTok: 0.11},
	"glm-4.5-air": {InputPerMTok: 0.2, OutputPerMTok: 1.1, CacheReadPerMTok: 0.03},
}

// defaultsAsOf is when the table above was generated. Exposed through
// AsOf when no remote snapshot is installed, so a caller can tell how
// old the rates behind a cost figure are.
var defaultsAsOf = "2026-08-02T22:34:49Z"
